# Generated by Django 4.2.30 on 2026-09-30 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorScorecard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("evaluation_period", models.CharField(max_length=50)),
                (
                    "delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100 score based on GRN timeliness",
                        max_digits=5,
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100 score based on rejection rate",
                        max_digits=5,
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0-100 score based on price variance",
                        max_digits=5,
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2, help_text="0-100 score based on SLA/KYC", max_digits=5
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall weighted performance score",
                        max_digits=5,
                    ),
                ),
                ("evaluator_comments", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluated_scorecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
